/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BrassSection: typeof import('./src/components/BrassSection.vue')['default']
    ChamberSection: typeof import('./src/components/ChamberSection.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Recipe: typeof import('./src/components/Recipe.vue')['default']
    RecipeForm: typeof import('./src/components/RecipeForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
